import { Injectable } from '@nestjs/common';

interface BrandProfile {
  toneOfVoice?: string;
  styleKeywords?: string[];
  prohibitions?: string[];
  sampleContent?: string;
  primaryColor?: string;
  secondaryColor?: string;
}

interface GenerationContext {
  clientName: string;
  industry: string;
  brief: string;
  type: string; // POST, REEL, STORY, CAROUSEL
  platform?: string;
  brandProfile: BrandProfile;
  index: number; // For variation
  notebookContext?: string; // Brand Notebook content
}

@Injectable()
export class PromptBuilderService {
  /**
   * Build the system prompt with brand context
   */
  buildSystemPrompt(ctx: GenerationContext): string {
    const parts = [
      `You are a senior social media content creator specializing in ${ctx.industry || 'general'} brands.`,
      `You create content for the brand "${ctx.clientName}".`,
    ];

    if (ctx.brandProfile?.toneOfVoice) {
      parts.push(`Brand tone of voice: ${ctx.brandProfile.toneOfVoice}`);
    }

    if (ctx.brandProfile?.styleKeywords?.length) {
      parts.push(`Style keywords: ${ctx.brandProfile.styleKeywords.join(', ')}`);
    }

    if (ctx.brandProfile?.prohibitions?.length) {
      parts.push(`NEVER use or mention: ${ctx.brandProfile.prohibitions.join(', ')}`);
    }

    if (ctx.brandProfile?.sampleContent) {
      parts.push(`Example of approved content style:\n"${ctx.brandProfile.sampleContent}"`);
    }

    if (ctx.notebookContext) {
      parts.push(`\n--- Brand Knowledge Base ---\n${ctx.notebookContext}\n---`);
    }

    parts.push(
      'Respond ONLY with the requested content in JSON format.',
      'All content must be in the same language as the brief.',
    );

    return parts.join('\n');
  }

  /**
   * Build the user prompt based on content type
   */
  buildUserPrompt(ctx: GenerationContext): string {
    const typePrompts: Record<string, string> = {
      POST: this.buildPostPrompt(ctx),
      REEL: this.buildReelPrompt(ctx),
      STORY: this.buildStoryPrompt(ctx),
      CAROUSEL: this.buildCarouselPrompt(ctx),
    };

    return typePrompts[ctx.type] || typePrompts.POST;
  }

  /**
   * Get the task type for AI routing
   */
  getTaskType(contentType: string): string {
    const map: Record<string, string> = {
      POST: 'generate:post:caption',
      REEL: 'generate:reel:script',
      STORY: 'generate:story:creative',
      CAROUSEL: 'generate:carousel:narrative',
    };
    return map[contentType] || 'generate:post:caption';
  }

  private buildPostPrompt(ctx: GenerationContext): string {
    const variationNote = ctx.index > 0
      ? `This is variation #${ctx.index + 1}: make it DISTINCTLY different in angle and hook from the previous ones.`
      : '';

    return `You are creating an ORIGINAL social media post for "${ctx.clientName}".

CREATIVE BRIEF (use as inspiration and strategic direction — do NOT copy or paraphrase it):
"""
${ctx.brief}
"""

YOUR TASK:
- Write a ${ctx.platform || 'social media'} post that feels native, human, and scroll-stopping
- The caption must FEEL like it was written by a real person, not generated by AI
- Open with a strong hook: a question, a bold claim, a surprising stat, or a relatable pain point
- Develop the idea creatively — tell a story, give value, provoke thought, or challenge an assumption
- Close with a clear CTA that feels natural and compelling
- DO NOT repeat or paraphrase the brief — use it only to understand the topic and goal
- Use emojis sparingly and naturally (only where they add meaning)
${variationNote}
${ctx.platform ? `Platform nuance: Write specifically for ${ctx.platform} audience expectations.` : ''}

Respond ONLY in this JSON format:
{
  "caption": "The full post text with natural emoji usage",
  "hook": "The exact opening line that stops the scroll",
  "cta": "The closing call to action",
  "hashtags": ["hashtag1", "hashtag2", "...up to 15 relevant hashtags"],
  "visualPrompt": "Detailed description of the ideal image/visual to pair with this post"
}`;
  }

  private buildReelPrompt(ctx: GenerationContext): string {
    const variationNote = ctx.index > 0
      ? `This is variation #${ctx.index + 1}: use a completely different opening hook and narrative structure.`
      : '';

    return `You are creating an ORIGINAL Reel/Short video script for "${ctx.clientName}".

CREATIVE BRIEF (use as strategic direction — do NOT copy it):
"""
${ctx.brief}
"""

YOUR TASK:
- Write a video script that would genuinely stop someone mid-scroll
- The first 2-3 seconds are EVERYTHING — open with a pattern interrupt: a provocative question, a bold statement, or an unexpected visual/action
- Keep energy high throughout — short sentences, punchy delivery
- Guide the viewer to a clear payoff and CTA at the end
- The script should feel like it comes from a real creator in this niche, not a brand robot
- DO NOT summarize the brief — create entirely original video content inspired by the goal
${variationNote}
${ctx.platform ? `Platform: optimize for ${ctx.platform} format and audience.` : ''}

Respond ONLY in this JSON format:
{
  "hook": "The exact first 2-3 seconds — what the creator says or does",
  "script": "Full script with timestamps. Format: [00:00] Scene/action description — Spoken text or on-screen text",
  "caption": "The post caption for this reel",
  "cta": "The closing call to action (spoken and/or on-screen)",
  "hashtags": ["hashtag1", "hashtag2", "...up to 15"],
  "duration": "Estimated duration: 15, 30, 60, or 90 seconds",
  "visualPrompt": "Key visual style, scenes, and on-screen text overlays description"
}`;
  }

  private buildStoryPrompt(ctx: GenerationContext): string {
    const variationNote = ctx.index > 0
      ? `This is variation #${ctx.index + 1}: use a different format (e.g., poll, quiz, countdown, or behind-the-scenes).`
      : '';

    return `You are creating an ORIGINAL Instagram/Facebook Story for "${ctx.clientName}".

CREATIVE BRIEF (use as strategic direction — do NOT copy it):
"""
${ctx.brief}
"""

YOUR TASK:
- Stories are fast and visual — keep text minimal and impactful
- The opening must create immediate curiosity or FOMO
- Use the ephemeral, personal nature of Stories — feel intimate and direct, like a friend sharing something
- The CTA must feel urgent and low-friction ("tap here", "swipe up", "reply now")
- DO NOT paraphrase the brief — create fresh Story content that serves the same goal
${variationNote}
${ctx.platform ? `Platform: ${ctx.platform}` : ''}

Respond ONLY in this JSON format:
{
  "hook": "Opening text that creates instant curiosity (max 1 line)",
  "caption": "Main story text — short and punchy (max 2 lines)",
  "cta": "Action prompt text (e.g., 'Tap to find out →')",
  "hashtags": ["hashtag1", "hashtag2", "...up to 5"],
  "visualPrompt": "Background image/video description — color, mood, style",
  "stickerSuggestions": ["poll/quiz/question/countdown suggestion if relevant"]
}`;
  }

  private buildCarouselPrompt(ctx: GenerationContext): string {
    const variationNote = ctx.index > 0
      ? `This is variation #${ctx.index + 1}: use a completely different angle, number of slides, and narrative structure.`
      : '';

    return `You are creating an ORIGINAL Carousel post for "${ctx.clientName}".

CREATIVE BRIEF (use as strategic direction — do NOT copy it):
"""
${ctx.brief}
"""

YOUR TASK:
- Carousels are the highest-engagement format — use them to teach, reveal, or tell a story across slides
- The COVER slide must create irresistible curiosity to make people swipe
- Each slide should deliver ONE clear, valuable idea — no clutter
- Build narrative momentum: each slide should make the reader want the next one
- The final slide closes with a strong CTA and often a recap
- Write each slide as if it's a standalone piece, but with a thread connecting them all
- DO NOT copy the brief — create original educational or narrative content that serves the goal
${variationNote}
${ctx.platform ? `Platform: ${ctx.platform}` : ''}

Respond ONLY in this JSON format:
{
  "caption": "The main post caption (shown in feed before swiping)",
  "hook": "Cover slide text — the headline that makes people swipe right NOW",
  "slides": [
    { "title": "Slide headline (short, punchy)", "body": "Slide body — 1 key idea, 2-3 sentences max", "visualPrompt": "Visual/design direction for this slide" }
  ],
  "cta": "Final slide call to action",
  "hashtags": ["hashtag1", "hashtag2", "...up to 15"]
}`;
  }
}
